apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ms-api-events
  labels:
    app: ms-api-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-api-events
  template:
    metadata:
      labels:
        app: ms-api-events
    spec:
      containers:
      - name: ms-dal-talks
        image: gcr.io/kubernetes-101-227215/ms-api-events:latest
        env:
        - name: API_SPEAKERS
          valueFrom:
            configMapKeyRef:
              name: ms-api-events-env
              key: API_SPEAKERS
        - name: API_TALKS
          valueFrom:
            configMapKeyRef:
              name: ms-api-events-env
              key: API_TALKS
        ports:
        - name: api-events
          containerPort: 9093
          protocol: TCP