swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Events Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: events-api.endpoints.kubernetes-101-227215.cloud.goog
basePath: "/"
tags:
- name: graphi-ql-controller
  description: Graphi QL Controller
- name: event-controller
  description: Event Controller
- name: basic-error-controller
  description: Basic Error Controller
paths:
  "/error":
    get:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingGET
      consumes:
      - application/json
      produces:
      - text/html
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/ModelAndView"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    head:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingHEAD
      consumes:
      - application/json
      produces:
      - text/html
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/ModelAndView"
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingPOST
      consumes:
      - application/json
      produces:
      - text/html
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/ModelAndView"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingPUT
      consumes:
      - application/json
      produces:
      - text/html
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/ModelAndView"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingDELETE
      consumes:
      - application/json
      produces:
      - text/html
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/ModelAndView"
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    options:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingOPTIONS
      consumes:
      - application/json
      produces:
      - text/html
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/ModelAndView"
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    patch:
      tags:
      - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingPATCH
      consumes:
      - application/json
      produces:
      - text/html
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/ModelAndView"
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  "/graphiql":
    get:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    head:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingHEAD
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingPUT
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingDELETE
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    options:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingOPTIONS
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    patch:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingPATCH
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  "/speakers":
    get:
      tags:
      - event-controller
      summary: findAll
      operationId: findAllUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Iterable«Speaker»"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/speakers/{id}":
    get:
      tags:
      - event-controller
      summary: findById
      operationId: findByIdUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Speaker"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/talks":
    get:
      tags:
      - event-controller
      summary: findAllTalks
      operationId: findAllTalksUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Iterable«Talk»"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/talks/{id}":
    get:
      tags:
      - event-controller
      summary: findByIdTalk
      operationId: findByIdTalkUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Talk"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  Iterable«Talk»:
    type: object
  ModelAndView:
    type: object
    properties:
      empty:
        type: boolean
      model:
        type: object
      modelMap:
        type: object
        additionalProperties:
          type: object
      reference:
        type: boolean
      status:
        type: string
        enum:
        - '100'
        - '101'
        - '102'
        - '103'
        - '200'
        - '201'
        - '202'
        - '203'
        - '204'
        - '205'
        - '206'
        - '207'
        - '208'
        - '226'
        - '300'
        - '301'
        - '302'
        - '302'
        - '303'
        - '304'
        - '305'
        - '307'
        - '308'
        - '400'
        - '401'
        - '402'
        - '403'
        - '404'
        - '405'
        - '406'
        - '407'
        - '408'
        - '409'
        - '410'
        - '411'
        - '412'
        - '413'
        - '413'
        - '414'
        - '414'
        - '415'
        - '416'
        - '417'
        - '418'
        - '419'
        - '420'
        - '421'
        - '422'
        - '423'
        - '424'
        - '426'
        - '428'
        - '429'
        - '431'
        - '451'
        - '500'
        - '501'
        - '502'
        - '503'
        - '504'
        - '505'
        - '506'
        - '507'
        - '508'
        - '509'
        - '510'
        - '511'
      view:
        "$ref": "#/definitions/View"
      viewName:
        type: string
  Iterable«Speaker»:
    type: object
  Talk:
    type: object
    properties:
      endTime:
        type: string
      id:
        type: integer
        format: int32
      idSpeaker:
        type: integer
        format: int32
      name:
        type: string
      speaker:
        "$ref": "#/definitions/Speaker"
      startTime:
        type: string
  View:
    type: object
    properties:
      contentType:
        type: string
  Speaker:
    type: object
    properties:
      bio:
        type: string
      id:
        type: integer
        format: int32
      name:
        type: string
