swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Events Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: events-api.endpoints.kubernetes-101-227215.cloud.goog
basePath: "/"
tags:
- name: graphi-ql-controller
  description: Graphi QL Controller
- name: event-controller
  description: Event Controller
- name: basic-error-controller
  description: Basic Error Controller
paths:
  "/graphiql":
    get:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    head:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingHEAD
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingPUT
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingDELETE
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    options:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingOPTIONS
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    patch:
      tags:
      - graphi-ql-controller
      summary: graphiql
      operationId: graphiqlUsingPATCH
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  "/speakers":
    get:
      tags:
      - event-controller
      summary: findAll
      operationId: findAllUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Iterable«Speaker»"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/speakers/{id}":
    get:
      tags:
      - event-controller
      summary: findById
      operationId: findByIdUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Speaker"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/talks":
    get:
      tags:
      - event-controller
      summary: findAllTalks
      operationId: findAllTalksUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Iterable«Talk»"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/talks/{id}":
    get:
      tags:
      - event-controller
      summary: findByIdTalk
      operationId: findByIdTalkUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Talk"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  Iterable«Talk»:
    type: object
  Iterable«Speaker»:
    type: object
  Talk:
    type: object
    properties:
      endTime:
        type: string
      id:
        type: integer
        format: int32
      idSpeaker:
        type: integer
        format: int32
      name:
        type: string
      speaker:
        "$ref": "#/definitions/Speaker"
      startTime:
        type: string
  Speaker:
    type: object
    properties:
      bio:
        type: string
      id:
        type: integer
        format: int32
      name:
        type: string
